yalla-notlop/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}
  get 'welcome/index'
  resources :users, only: [:show]

  post "/orders/invite.json", to: "invited_members#invite"
   
  resources :friends, only: [:index, :create, :destroy, :update]
  get "/friends/:id/cancel", to: "friends#cancel", as: "cancel_request"
  resources :orders do
    get "/joined/", to: "order_informations#index"
    post"/add/", to: "order_informations#create"
    get "/invited/", to: "invited_members#index"
  end

  resources :groups do
    resources :members
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

yalla-notlop/app/views/layouts/_navbar.html.erb
    <div class="row mb-4">
        <div class="col-12">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
            <%= link_to "YallaNotlob", welcome_index_path, :class => 'navbar-brand' %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <%= link_to "Home", welcome_index_path, :class => 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "Friends", friends_path, :class => 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "Groups", groups_path, :class => 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "Orders", orders_path, :class => 'nav-link' %>
                </li>
              </ul>
              <ul class="navbar-nav">
                <% if user_signed_in? %>
                    <li class="nav-item">
                      <%= image_tag current_user.profile_pic.url(:thumb), class: "rounded-circle" %>
                    </li>
                    <li class="nav-item">
                      <strong class="mx-2"><%= link_to current_user.name, user_path(current_user), :class => 'nav-link' %></strong>
                    </li>
                    <li class="nav-item">
                       <strong class="mx-2"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %></strong>
                    </li>
                    <li class="nav-item">
                      <strong class="mx-2"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %></strong>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <strong class="mx-2"><i class="fa fa-bell"></i></strong>
                      </a>
                      <ul class="dropdown-menu">
                        <li class="head text-light bg-dark">
                          <div class="row">
                            <div class="col-lg-12 col-sm-12 col-12">
                              <span>Notifications (3)</span>
                              <a href="" class="float-right text-light">Mark all as read</a>
                            </div>
                        </li>
                        <li class="notification-box">
                          <div class="row">
                            <div class="col-lg-3 col-sm-3 col-3 text-center">
                              <img src="/demo/man-profile.jpg" class="w-50 rounded-circle">
                            </div>    
                            <div class="col-lg-8 col-sm-8 col-8">
                              <strong class="text-info">David John</strong>
                              <div>
                                Lorem ipsum dolor sit amet, consectetur
                              </div>
                              <small class="text-warning">27.11.2015, 15:00</small>
                            </div>    
                          </div>
                        </li>
                        <li class="notification-box bg-gray">
                          <div class="row">
                            <div class="col-lg-3 col-sm-3 col-3 text-center">
                              <img src="/demo/man-profile.jpg" class="w-50 rounded-circle">
                            </div>    
                            <div class="col-lg-8 col-sm-8 col-8">
                              <strong class="text-info">David John</strong>
                              <div>
                                Lorem ipsum dolor sit amet, consectetur
                              </div>
                              <small class="text-warning">27.11.2015, 15:00</small>
                            </div>    
                          </div>
                        </li>
                        <li class="footer bg-dark text-center">
                          <a href="" class="text-light">View All</a>
                        </li>
                      </ul>
                </li>
                <% else %>
                    <li class="nav-item">
                      <strong class="mx-2"><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link float-right'  %></strong>
                    </li>
                    <li class="nav-item">
                      <strong class="mx-2"><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></strong>
                    </li>
                <% end %>
                
              </ul>
            </div>
          </nav>
        </div>
    </div>
    </div>

yalla-notlop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YallaNotlop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="container">
        <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
          <%= link_to "Groups", groups_path, :class => 'navbar-link'  %>
          <%= link_to "Orders", orders_path, :class => 'navbar-link'  %>

      </p>
        <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
          <%= yield %>
    </div>
  </body>
</html>