yalla-notlop/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}
  get 'welcome/index'
  resources :users, only: [:show]

  post "/orders/invite.json", to: "invited_members#invite"
   
  resources :friends, only: [:index, :create, :destroy, :update]
  get "/friends/:id/cancel", to: "friends#cancel", as: "cancel_request"
  resources :orders do
    get "/joined/", to: "order_informations#index"
    post"/add/", to: "order_informations#create"
    get "/invited/", to: "invited_members#index"
  end

  resources :groups do
    resources :members
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

yalla-notlop/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = current_user
    @orders = @user.orders.order(created_at: :desc)
    @friends_activities = Order.where(user_id: @user.friends.select(:id)).joins(:user).select("orders.*, users.name as username").order(created_at: :desc)
  end
end

yalla-notlop/app/helpers/welcome_helper.rb
module WelcomeHelper
end

yalla-notlop/app/views/welcome/index.html.erb
<div class="row">
    <div class="col-6">
        <%= link_to 'create order', new_order_path, class: "btn btn-success float-right mb-4 mr-4"%>
        <h3>My Orders</h3>
        
            <% @orders.each do |order| %>
                <% unless order.cancelled? %>
                <div class="row mt-4">
                        <%= link_to order.name + " " + order.meal + " on " + distance_of_time_in_words(Time.now, order.ends_at) + " from " + order.resturant + " ("+order.status+")", order_path(order.id) %>     
                </div>
                <% end %>
            <% end %>
    </div>

    <div class="col-6">
        <h3>Friend's Activities</h3>
        
            <% @friends_activities.each do |order| %>
                <div class="row mt-4">
                    <% unless order.cancelled? %>
                    <p>
                        <%= link_to order.name + " " + order.meal + " on " + distance_of_time_in_words(Time.now, order.ends_at) + " from " + order.resturant + " ("+order.status+")", order_path(order.id) %>
                         by <%= link_to  "@"+order.username, user_path(order.user_id) %>   
                    </p>  
                    <% end %>
                </div>
            <% end %>
    </div>
</div>