yalla-notlop/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}
  get 'welcome/index'
  resources :users, only: [:show]

  post "/orders/invite.json", to: "invited_members#invite"
   
  resources :friends, only: [:index, :create, :destroy, :update]
  get "/friends/:id/cancel", to: "friends#cancel", as: "cancel_request"
  resources :orders do
    get "/joined/", to: "order_informations#index"
    post"/add/", to: "order_informations#create"
    get "/invited/", to: "invited_members#index"
  end

  resources :groups do
    resources :members
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

yalla-notlop/app/models/order.rb
class Order < ApplicationRecord

  #relationships
  belongs_to :user
  has_many :invited_members, dependent: :destroy
  has_many :order_informations, dependent: :destroy
  has_many :order_notifications, dependent: :destroy
  has_attached_file :menu, styles: { large: "900x900>", thumb: "100x100>" }

  #enumarations
  enum status: [:waiting, :finished, :cancelled]
  enum meal: [:breakfast, :lunch, :dinner]
  
  #calidations
  validates_attachment_content_type :menu, content_type: /\Aimage\/.*\z/
  validates_inclusion_of :status, :in => %w( waiting finished cancelled )
  validates_inclusion_of :meal, :in => %w( breakfast lunch dinner )
  validates :name, presence: true 
  validates :ends_at, presence: true
  validates :meal, presence: true 
  validates :resturant, presence: true 
  validates :menu, presence: true 
  validate :ends_at_in_future

  def ends_at_in_future
    errors.add(:ends_at, "must be some date in the future.") if ends_at <= DateTime.now
  end
  
end

yalla-notlop/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :get_user, except: [:show]

    #GET /orders
    def index
        @orders = @user.orders.order(created_at: :desc)
    end

    #GET /orders/new
    def new
        @order = @user.orders.build
    end

    #POST /orders
    def create
        @order = @user.orders.build(get_order_params)
        @order.status = :waiting
        #check if submitted data are valid.
        (render "new" and return) unless @order.save
        make_invitations()
        redirect_to order_path @order
    end

    #GET orders/:id/edit
    def edit
        @order = @user.orders.find_by(id: params[:id])
        #redirect to orders index if not an exited order or the order is not still waiting
        (redirect_to orders_path and return) if (@order == nil or not @order.waiting?)
        @invited_members = @order.invited_members.joins(:user).select("users.*")
    end

    #PUT /orders/:id
    def update
        @order = @user.orders.find_by(id: params[:id])
        (render "edit" and return) if get_order_params[:ends_at] >= DateTime.now
        @order.update(get_order_params) if @order.waiting?
        make_invitations()
        redirect_to order_path @order

    end

    #GET /orders/:id
    def show
        @order = Order.find_by(id: params[:id])
        (redirect_to orders_path and return) unless @order
        @order.finished! if @order.ends_at <= DateTime.now
        @order_informations = @order.order_informations.all
    end

    #DELETE /order/:id
    def destroy
        @order = @user.orders.find_by(id: params[:id])
        @order.cancelled! if @order
        redirect_to orders_path and return
    end

    private
    def get_user
        @user = current_user
    end

    def get_order_params
        params.require(:order).permit(:name, :menu, :resturant, :meal, :ends_at)
    end
    
    def make_invitations
        @invited_people = params[:order][:invited_ids].split(",").uniq
        @invited_ids = []
        @order.invited_members.select(:user_id).each {|r| @invited_ids.push(r.user_id.to_s)}
        @invited_people.each do |invited_id|
            unless @invited_ids.include?(invited_id)
                @order.invited_members.create(user_id: invited_id)
                @order.order_notifications.create(from: @user, to_id: invited_id, status: :unread)
            end
        end
    end

end

yalla-notlop/app/helpers/orders_helper.rb
module OrdersHelper
end

yalla-notlop/app/views/orders/_form.html.erb
<%= form_with model: @order, local: true, id: "order" do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li style="color:red"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      
      <%= f.hidden_field :invited_ids %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :name, "For" %>
        <select name="order[meal]" id="order_meal" class="form-control">
          <option value="breakfast" selected>BreakFast</option>
          <option value="lunch">Lunch</option>
          <option value="dinner">Dinner</option>
        </select>
    </div>

    <div class="form-group">
      <%= f.label :resturant %>
      <%= f.text_field :resturant, class:"form-control" %>
    </div>

      <%= f.label :invite %><br />
      <%= f.text_field :invitations , id: "invite-box", class: "form-control" %> 
    <button class="btn btn-primary my-2" id="invite-btn">invite</button>
    <div class="form-group">
      <%= f.datetime_field :ends_at %>
    </div>
    <div class="form-group">
      <%= f.file_field :menu %>
    </div>
    <div class="form-group">
      <%= f.submit "add", class: "btn btn-primary" %>
    </div>
<% end %>

yalla-notlop/app/views/orders/_form_invite.html.erb
<%= form_with model: [@order, @friend], local: true, class: "mb-4" do |f| %>

  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-row">
        <div class="col-9">
        <%= f.text_field :name, class: "form-control", placeholder: "member name" %>
        </div>
        <div class="col-3">
        <%= f.submit "add", class: "btn btn-primary"%>
        </div>
    </div>
<% end %>

yalla-notlop/app/views/orders/edit.html.erb
<div class="row">
    <div class="col-6 mr-4">
        <h2>Editing Order</h2>
        <%= render 'form', order: @order %>
    </div>
    <div class="col-5 ml-4">
        <div class="row">
            <h2>Invited</h2>
        </div>
        <div class="row" id="invited-people-list">
        <% @invited_members.each do |invited_member| %>
            <div class='col-5 m-1'>
                <div class='row'>
                    <div class='col-4 mr-2'>
                        <img src='' width='70px' height='80px'/>
                        <div class='col-5 p-0 ml-4'>
                            <%= link_to  invited_member.name, user_path(invited_member), class: 'font-weight-bold' %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
        </div>
    </div>
</div>
    <%= link_to '<< back', orders_path %>

yalla-notlop/app/views/orders/index.html.erb
<h1>Orders</h1>

<%= link_to 'create order', new_order_path, class: "btn btn-success float-right mb-4"%>
<table class="table table-borderless">
  <thead>
    <tr>
      <th scope="col">Order</th>
      <th scope="col">For</th>
      <th scope="col">Restaurant</th>
      <th scope="col">Status</th>
      <th scope="col">Ends in</th>
      <th scope="col">Invited</th>
      <th scope="col">Joined</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
    <% unless order.cancelled? %>
      <tr>
        <th scope="row"><%= link_to order.name, order_path(order.id) %></th>
        <td><%= order.meal %></td>
        <td><%= order.resturant %></td>
        <td><%= order.status %></td>
        <td><%= distance_of_time_in_words(Time.now, order.ends_at) %></td>
        <td><%= order.invited_members.count %></td>
        <td><%= order.order_informations.select(:user_id).distinct.count %></td>
        <% unless order.finished? %>
          <td><%= link_to 'finish', edit_order_path(order.id) %></td>
          <td><%= link_to 'Cancel', order_path(order.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

yalla-notlop/app/views/orders/new.html.erb
<div class="row">
    <div class="col-6 mr-4">
        <h2>New Order</h2>
        <%= render 'form', order: @order %>
    </div>
    <div class="col-5 ml-4">
        <div class="row">
            <h2>Invited</h2>
        </div>
        <div class="row" id="invited-people-list">
        </div>
    </div>
</div>
    <%= link_to '<< back', orders_path %>

yalla-notlop/app/views/orders/show.html.erb
<h1>Order details</h1>
<table class="table table-borderless">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Item</th>
      <th scope="col">amount</th>
      <th scope="col">price</th>
      <th scope="col">comment</th>
    </tr>
  </thead>
<% @order_informations.each do |ordermember| %>
  <tbody>
      <tr>
        <td><%= ordermember.user.name %></td>
        <td><%= ordermember.item_name %></td>
        <td><%= ordermember.amount %></td>
        <td><%= ordermember.item_price %></td>
        <td><%= ordermember.comment %></td>
      </tr>
<% end %>
  </tbody>
</table>

<%= link_to "#{@order.invited_members.count} friends invited, click to view", order_invited_path(@order) %>
<br>
<%= link_to "#{@order.order_informations.select(:user_id).distinct.count} friends joined, click to view", order_joined_path(@order) %>

<% if @order.waiting? %>
  <h2>Add item:</h2>
  <%= form_with scope: "order_informations", url: order_add_path(@order), method: :post, local: true, class: "form-inline" do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :order_id, value: @order.id %>
      <%= f.text_field :item_name, class: "form-control mb-2 mr-sm-2", placeholder: "item name" %>
      <%= f.text_field :amount, class: "form-control mb-2 mr-sm-2", placeholder: "amount" %>
      <%= f.text_field :item_price, class: "form-control mb-2 mr-sm-2", placeholder: "item price" %>
      <%= f.text_field :comment, class: "form-control mb-2 mr-sm-2", placeholder: "comment" %>

    <div class="actions">
      <%= f.submit "add", class:"btn btn-primary mb-2"%>
    </div>
  <% end %>
<% end %>