yalla-notlop/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}
  get 'welcome/index'
  resources :users, only: [:show]

  post "/orders/invite.json", to: "invited_members#invite"
   
  resources :friends, only: [:index, :create, :destroy, :update]
  get "/friends/:id/cancel", to: "friends#cancel", as: "cancel_request"
  resources :orders do
    get "/joined/", to: "order_informations#index"
    post"/add/", to: "order_informations#create"
    get "/invited/", to: "invited_members#index"
  end

  resources :groups do
    resources :members
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

yalla-notlop/app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :members, dependent: :destroy
end

yalla-notlop/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :get_user, only: [:show, :index]
    before_action :get_user_groups, only: [:show, :index]
    
    def index
        @group = Group.new
    end

    def show
        @this_group = @user.groups.find_by(id: params[:id])
        unless @this_group
            redirect_to groups_path
        end
        @members = @this_group.members.joins(:user).select(:name, :email, :user_id, :group_id)
        @group = Group.new
        @member = @this_group.members.build
    end

    def create
        @newgroup = current_user.groups.create(get_group_params)
        redirect_to groups_path
    end

    def destroy
        Group.find(params[:id]).destroy
        redirect_to groups_path
    end

    private
    def get_group_params
        params.require(:group).permit(:name)
    end
    def get_user
        @user = current_user
    end
    def get_user_groups
        @groups = @user.groups.all
    end
end

yalla-notlop/app/helpers/groups_helper.rb
module GroupsHelper
end

yalla-notlop/app/views/groups/_form_group.html.erb
<%= form_for(@group) do |f| %>

  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-row">
        <div class="col-9">
        <%= f.text_field :name, class: "form-control", placeholder: "group name" %>
        </div>
        <div class="col-3">
        <%= f.submit "create", class: "btn btn-primary"%>
        </div>
    </div>
<% end %>

yalla-notlop/app/views/groups/_form_member.html.erb
<%= form_with model: [@this_group, @member], local: true, class: "mb-4" do |f| %>

  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-row">
        <div class="col-9">
        <%= f.text_field :name, class: "form-control", placeholder: "member name" %>
        </div>
        <div class="col-3">
        <%= f.submit "add", class: "btn btn-primary"%>
        </div>
    </div>
<% end %>

yalla-notlop/app/views/groups/_group_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Gruops</h1>

<%= render "form_group" %>

<div class="row mt-4">
    <div class="col-4 p-2">
        <h3 class="mb-4">My Groups</h3>
        <% @groups.each do |group| %>
            <div class="group mb-4">
                <%= link_to group.name, group_path(group), class: "p-1 mr-4 group-name"%>
                <%= link_to 'edit', edit_group_path(group), class: "p-1 mr-4" %>
                <%= link_to 'delete', group_path(group), method: :delete, class: "btn btn-danger p-1 mr-4", data: { confirm: 'Are you sure?' } %>
                <br>
            </div>
        <% end %>
    </div>
    <div class="col-8 p-2">
        <%= yield %>
    </div>

</div>

yalla-notlop/app/views/groups/index.html.erb
<%= render partial: "group_list" %>

yalla-notlop/app/views/groups/show.html.erb
<%= render layout: "group_list" do %>
    <div class="row justify-content-center">
        <h3><%= @this_group.name %> members</h3>
    </div>
    <%= render "form_member" %>
    <div class="row">
    <% @members.each do |member| %>
        <div class="m-1 col-5">
            <div class="row">
                <div class="col-4">
                    <img src="" width="70px" height="80px">
                </div>
                <div class="col-5 p-0">
                    <%= link_to member.name, user_path(member.user_id), class: "font-weight-bold"%><br>
                    <%= link_to  "remove", group_member_path(member.group_id, member.user_id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %><br>
                </div>
            </div>
        </div>
    <% end %>
    </div>
<% end %>